[bot]
token = "TOKEN"

[database]
models = ["app.db.functions", "aerich.models"]

[storage] # (Optional) Persistent FSM Storage for aiogram and aiogram_dialog, disabled by default
use_persistent_storage = false # (Optional)
# redis_url = "redis://user:password@host:port/db" # (Optional) Redis URL for FSM storage

[settings]
owner_id = 123
throttling_rate = 0.5
drop_pending_updates = false

[api] # API app settings for Pyrogram Client
# Default values are from Telegram Desktop Client (t.me/durovleaks/108)
# bot_api_url = "https://api.telegram.org" # (Optional) Bot API URL
